# Generated by Django 4.2.5 on 2023-11-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=40)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_num', models.IntegerField(default=-1)),
                ('workspace', models.CharField(max_length=30)),
                ('months_period', models.IntegerField()),
                ('stmt', models.TextField(default='')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Qualified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=-1)),
                ('type', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_title', models.CharField(default='', max_length=50)),
                ('qualified_apply', models.CharField(max_length=20)),
                ('qualified_education', models.CharField(max_length=20)),
                ('qualified_disabled', models.CharField(max_length=25)),
                ('qualified_advantage', models.CharField(max_length=25)),
                ('hire_type', models.CharField(max_length=25)),
                ('hire_contract', models.CharField(default='', max_length=25)),
                ('hire_pay', models.CharField(max_length=25)),
                ('hire_region', models.CharField(max_length=25)),
                ('hire_rank', models.CharField(default='', max_length=25)),
                ('hire_role', models.CharField(default='', max_length=25)),
                ('submit_period', models.CharField(default='', max_length=50)),
                ('submit_type', models.CharField(max_length=25)),
                ('submit_address', models.CharField(max_length=25)),
                ('submit_portpolio', models.CharField(default='', max_length=25)),
                ('work_region', models.CharField(max_length=25)),
                ('work_day', models.CharField(max_length=25)),
                ('work_period', models.CharField(max_length=25)),
                ('work_benefits', models.CharField(default='', max_length=25)),
                ('work_facility', models.CharField(default='', max_length=25)),
                ('officer_name', models.CharField(max_length=25)),
                ('officer_tel', models.CharField(max_length=25)),
                ('officer_email', models.CharField(default='@', max_length=25)),
                ('user_id', models.ManyToManyField(null=True, related_name='hires', to='fatherapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=-1)),
                ('type', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=50)),
                ('how', models.CharField(max_length=200)),
                ('user_id', models.ManyToManyField(null=True, related_name='benefits', to='fatherapp.user')),
            ],
        ),
    ]
