# Generated by Django 4.2.5 on 2023-11-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='qualified',
            name='num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_num',
            field=models.IntegerField(default=-1, unique=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_num',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
