# Generated by Django 4.2.5 on 2023-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0003_characteristics_num_qualified_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_num',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='statement',
            name='statement_num',
            field=models.IntegerField(default=-1),
        ),
    ]
