# Generated by Django 4.2.5 on 2023-11-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0004_alter_resume_resume_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user'),
        ),
        migrations.AlterField(
            model_name='qualified',
            name='user_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user'),
        ),
    ]
