# Generated by Django 4.2.5 on 2023-11-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0006_alter_characteristics_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user'),
        ),
    ]
