# Generated by Django 4.2.5 on 2023-11-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0008_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_id', models.CharField(default=-1, max_length=20)),
                ('qualified_apply', models.CharField(max_length=20)),
                ('qualified_education', models.CharField(max_length=20)),
                ('qualified_disabled', models.CharField(max_length=25)),
                ('qualified_advantage', models.CharField(max_length=25)),
                ('hire_type', models.CharField(max_length=25)),
                ('hire_pay', models.CharField(max_length=25)),
                ('hire_region', models.CharField(max_length=25)),
                ('submit_type', models.CharField(max_length=25)),
                ('submit_address', models.CharField(max_length=25)),
                ('work_region', models.CharField(max_length=25)),
                ('work_day', models.CharField(max_length=25)),
                ('work_period', models.CharField(max_length=25)),
                ('work_facility', models.CharField(max_length=25)),
                ('officer_name', models.CharField(max_length=25)),
                ('officer_tel', models.CharField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatherapp.user')),
            ],
        ),
    ]
