# Generated by Django 4.2.5 on 2023-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0011_hire_hire_rank_hire_hire_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='user_id',
        ),
        migrations.AddField(
            model_name='hire',
            name='user_id',
            field=models.ManyToManyField(null=True, to='fatherapp.user'),
        ),
    ]
