# Generated by Django 4.2.5 on 2023-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatherapp', '0014_welfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='hire_contract',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='hire',
            name='submit_portpolio',
            field=models.CharField(default='', max_length=25),
        ),
    ]
